services:
  stub:
    # mockoon/cli:9.8.0
    image: mockoon/cli@sha256:2a087214049f3c19780ee7216c43c863469a4e5639b5690adabf349d670687aa
    volumes:
      - ./config/mockoon/line-api.json:/data/line-api.json:ro
    command: ["-d", "/data/line-api.json", "-p", "3000"]
    networks:
      - local-net

  otel-collector:
    # otel/opentelemetry-collector-contrib:0.158.0
    image: otel/opentelemetry-collector-contrib@sha256:c5918f78992ee73b0d6f0e599423ac5ec52dd5d9726733114d6eca53d5a32ed5
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4318:4318"
    networks:
      - local-net
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    # jaegertracing/all-in-one:1.76.0
    image: jaegertracing/all-in-one@sha256:ab6f1a1f0fb49ea08bcd19f6b84f6081d0d44b364b6de148e1798eb5816bacac
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
    networks:
      - local-net

  prometheus:
    # prom/prometheus:v3.13.2
    image: prom/prometheus@sha256:508729e0e2d18e11fd742a5a5ca70e557b940a93948c3c95fd0123a6fd538b69
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - local-net

  grafana:
    # grafana/grafana:13.1.3
    image: grafana/grafana@sha256:ab5cb380e3ff3172d6c8bd2e7cfd31cce977d2881b260e1f5bc089bf0b759b43
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    networks:
      - local-net
    depends_on:
      - prometheus

  lambda:
    build:
      context: .
      dockerfile: Containerfile
    entrypoint:
      - /usr/local/bin/aws-lambda-rie
    command:
      - opentelemetry-instrument
      - python
      - -m
      - awslambdaric
      - nandemo_oshirase.lambda_function.lambda_handler
    ports:
      - "9000:8080"
    networks:
      - local-net
    env_file:
      - .env.local
    environment:
      LINE_API_BASE_URL: http://stub:3000
      OTEL_SERVICE_NAME: nandemo-oshirase
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: DELTA
    depends_on:
      - stub
      - otel-collector

networks:
  local-net:
    driver: bridge
